# A sample Gemfile
source "https://rubygems.org"

ruby '1.9.3'
gemspec

gem 'trollop'
gem 'pry'

group :test do
	gem 'simplecov',	:require => false
	gem 'watchr', 		:require => false
end

group :development do
end
